# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-e24d5b44-c3a8-4f35-8850-aa11c901eab9";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-e24d5b44-c3a8-4f35-8850-aa11c901eab9" = {
    device = "/dev/disk/by-uuid/e24d5b44-c3a8-4f35-8850-aa11c901eab9";
    allowDiscards = true;
    keyFileSize = 4096;
    keyFile = "/dev/disk/by-id/usb-_Patriot_Memory_07B406013A4D761C-0:0";
    keyFileTimeout = 30;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0249-5787";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
