keys:
  - &admin_users:
    - &caperren       age1xjnkqv32a5nqftw6pqthapnzmgjl4lnqfpxy9utqm56yzm2mvfhqzch648
  - &systems:
    - &personal:
      - &cap_slim7    age1a5aqj3jr3rqpjet9a7y077ak0ymstjjdnyfgn5m2ad4l2yuxr4aqym7d3d
      - &cap_nr200p   age1g45zy9m5g4e20cjejgd3x40722rlddgkmhtddrl8wyf63kt5kg7s9ke390
    - &cluster:
      - &cap_clust_01 age1649y4antwgfe4fu02eppnx5gr0yc3g4lj4kwd6v9guxgxgj06y9qk7l4wl
      - &cap_clust_02 age1k085uuy4fv9rfpy0ne6zl9fq0j05a4fykqe26psx2ngxqrcxcu5sksxa9u
      - &cap_clust_03 age1tpeqfhc4n7swpgzx6qfdfxanx0uqh7nksr7eksnvjea70n8vaf5sntxu2l
      - &cap_clust_04 age1pux20jlyzdexztdmm3lelzn2mslxhuahae4wjy74hkxfytslsfpqj708e2
      - &cap_clust_05 age1f5039syajzz75s9lkdzwnv2dsvlcp69puuaucgwt05sqjdl7hels25nsfr
      - &cap_clust_06 age19m6f3xtkdf3gwxqxgp9w9gyla4hk24f85l2tyjx6dxu0akzux3cs657dhz
      - &cap_clust_07 age1en6vdtxspam9s3nmsyfrcrxzrzu4t9v72ztqyekpzsc35rd06a2sza7ehw
      - &cap_clust_08 age1vujvq5rdzppkkdhkwyhnl6xhuvm8s5yf2wc8ke05m8jwrdwsdf0qfx5w4r
      - &cap_clust_09 age1uyuudfya8etgztlt6hlssr9hkstyyhg65wdq3pj9rud2czzkaqqssg7yvp
creation_rules:
  - path_regex: users/caperren/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *caperren
          - *cap_slim7
          - *cap_nr200p
  - path_regex: secrets/default.yaml$
    key_groups:
      - age:
          - *caperren
          - *cap_slim7
          - *cap_nr200p
          - *cap_clust_01
          - *cap_clust_02
          - *cap_clust_03
          - *cap_clust_04
          - *cap_clust_05
          - *cap_clust_06
          - *cap_clust_07
          - *cap_clust_08
          - *cap_clust_09
  - path_regex: secrets/cluster.yaml$
    key_groups:
      - age:
          - *caperren
          - *cap_slim7
          - *cap_nr200p
          - *cap_clust_01
          - *cap_clust_02
          - *cap_clust_03
          - *cap_clust_04
          - *cap_clust_05
          - *cap_clust_06
          - *cap_clust_07
          - *cap_clust_08
          - *cap_clust_09
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *caperren
          - *cap_slim7
          - *cap_nr200p