# Unfortunate legacy config needed because hyprland can't hot switch variable refresh rate
monitor=,preferred,auto,auto

# Source configs
source = ~/.config/hypr/hyprland-common.conf

# Application launch
