accounts:
    root:
        hashed-password: ENC[AES256_GCM,data:WmZVlgKuhhr0giWDRmvGxanJb2xHC/mCZJ4w/g/bGVjUD26rcFAC+gSJXJd0k8OMzfQG1heW/ugpVoNLze7T9SyC3EmxeOUXVQ==,iv:okbRYi3vm1CesnO01QMWOuGMw9r1wTzUoJv68pcNZHQ=,tag:XtIDWn9XqLWf3iJmFns+Ew==,type:str]
    caperren:
        hashed-password: ENC[AES256_GCM,data:8pLgyZScZIi/gia0TQskZ0gnYboNbar73MPgTWQfKweEyUI8NotJfI/v6kXvGq2l41qAPhmjFyij5uOzYTwANpd+lonvSY4zog==,iv:cva/YYDULMuM/QoTiC/7BjVUs6nAy6+4gL9XenTWDAw=,tag:F66PTiXlnfx05rIW11EEvA==,type:str]
ssh:
    ilouser:
        id_rsa: ENC[AES256_GCM,data:BuoM1E1pf9srSfWWV+bIy9H/JAQIMsucJv8T+Sky6HgSsR1WLdOX8pYJSVukuMMisSBG8DJiGy7PgzqeZohrFbkaHpc7gI0S3+803pZQjILzs9kEIrpTzqb+i5UgGPNn7Q9Rk2Etm7UlQAaUSLZg1XfCWV421YeTDFnM42bLy8Lhpb5J/GyP4iYJN5osmlQdjUbzR4wWaYIofWHjTqbNo0yNdMTDPf/bVDw+/34Xx/Xcvc90KtbO/k/gWpOam/Mq/jMoaA0IcZu7p6pu3WWFlilkeBtLefLo8nDEGi13hT2KxrB89npTNWWXf4sejQxkZgp8x1FxA8LH9v6vRunvdBRNTw/JjmtxaF8vKfjd2oxaKztLA8NROYQRpavqv6/NGlyBCU+yncq/E5dl51t7BwDwpSUvYvVEP20qH1JBKtiyuHlLOTOwTJtigOE3EuNxuEViz56Q0tVpQOcPQuSRmwdOg8hMZx/HnaDv52JVxeQHdF8jpzz3E3noB1AbRIAb84XXWVo2QLxFb8W8t5ta5cdOq/Pqte5PNXfT+2pjBIOlfg5mzA9kjH4QOZaO7zBbMj/ZD480gZY+kUMgeXgOtoLSZCPvdBbSjd7Lsd7xYbZSk6m4jOtvbTzpaFX8ZIT4ompC/+G84t3HyxE+UUeBip7mTeOJBCc1WjguKSzdBMmYZUxJAGMmWJ+TQDZSFu2m7bMmLGTgya5isqtcqGN5cGcICxIfOVfuoJ5T6vO3t2ZdUuV2U4+gfCYhtEZbsT/lhgRC0NlMWBhowCRpzhowYLHHGqmUfl5M+JTCAOS1QDmZvaGVc8BC0WWkc+162NGME1D+GRolHF44TfB5IuTQ1cfrv+VvK4DIsEslleAMCxqHPPQPGpCTcCNfe/3Yylkl/Pmogas2P8Q1fyGVTZCsS2G5wugptt8AdfdM+tvmqzlyponw3lNKe+mj1ehunJ8V93ea95cdmVikM6OLykzSrbxsejX8EgIQ0BChAFly38ot7YcmqgfqABCGeiYwOnL/90EuRmYRaMuUihbiRVzGPd5oc0OKDj5xdM2Eq/VRaODCFuhmwK5eLHB3tGab2Bin/8VGZkpWjQsd3H/UYRfPpJqjnhI3/dxD619ouZPfsTfQCVnBaZMYVKzpmeb3geNMeV1h8cDxNsAk85nAnG6RUF7xlqmgF6yUZ/vFtjUq/vCoNHsKvS5sSy73LPXljrVvZyG2K9P6dfTR4n8yYGJCoj95ahCAD4djsr9ylRzj1YTFQ7XdZGxw3GML7rmzuMS/Kk0qMKNYSlS9ru0yIL2baZmntjUKjcl0qigzO74bi3TxyoylmxXA2/80AcRU/fWi0t9g9aTJmuVztPiRQpCLsDzSS/xTjriwThx6v7tgmVwO05SdlBQ5Fk6R1nOsC+4X35l2f6pWJ91nlkfimJM3mY/MZDxWusfgXcS3SBswj59n7zX7AwykcX6/XHVWg91EfB6sRUZyHWsMxwn+i/P5aoIiO43leCD9KX5T0KjRAxa0DG092zM6pRaKEJWeBXTgcFTS5AQdMLVlt5GBHBHw2Slr6SMsUo7A1ycJqP7nw+YdLje86h4edfvbAtowhaBT3WPFoxbtAoBWqkYPgTGs/AiKRsfjecypuCm52bz8VTiw8laRkYFO0nqyYZBm4u2BbVODS6Ji9ZxNpjN/NIDh/5ffhQ611iwL2xgob/yFrjqaRyzPx1DXseMO+Lc0TMEhdSVGG9i8fTJXN8VasDDHxWCQD/ZSyERGCqIDc1+pZBjwABiECsDtQy3DI+oQ3UEPLOFHGS95Kc5+KKij3ptvf61o2J6XKEUY0jqv+puNvmjz7jqsNBY+S524G+06zzcvXsUnWQ3o1lOseFDSl4ZV+a2GiRA+AHj5gSKXTNVUMDsEu7E+4Sg1WVFKLw4KgZ0KubHYQYz56QLojv2TUL3NrK1mUfdn9jeJ01L+CIMTVjz+4UjVI/AZJA370Le01pl0ZMxaFRa0fep1Pa6MikTS7SO8NBtTtbOI2Dt/hBrXpzbicfRU/2pNJ8hEn9in0eXkZ3h0/nHm5J/OrrbVOdvQK9RkF9J0sdgmLtnAxdQjKK7r8Tg17q4vefFRtTEFPz1hV8sOrNXJZc3GRnvINE/7CVYdBQZuq7Bqze9WS+Yqzo2Z7T+cgpLTThBWlL7uGRsNcOdxQOctvoHCDFMV+9+QSH9Cc55Jdbd1T/clludubmyCJLvd5+25haXtRNSivJ/qB/ZbaZq/1PrJw2rl9XuiTczVrG/5Gwpz7a7PVrP8ydIEoTAglMdr9WICKl2cqHo1+k7HOFZluJAugNTV5aRwCvb6roKXsENH6TE68RuiYI8GXD/AzrY86TADCZroeQ+arLW+UuDqQfsnJ6MM02NcSOriAqTbwikGSzNIwkOiuZmwc5Y1pVqe1pyVDf5gN6Q=,iv:IDe6vkBvgAzfxee+/odkLk1TLZRghVEf8hqH2r3+V9I=,tag:OFCA57fQjQxc+CT9DOq+VA==,type:str]
        id_rsa_pub: ENC[AES256_GCM,data:hYdf7KifFqkHDa8UF1zvhirc2AkrYpL2VrmV2IJjHzzgbrJxshdA629mTXwXwXORbLwNcMpRR7DFLyHCRDu5cWsxluZ04rNU9sJFmL+6pPUonaa4Wc+9z5VysV8UItY/BZ/5mOMQ2ph/wMQ3pkFnBD58vOFOYsmZ7OCir5dQZfm8GdGDX76bOlOI/CAg/LtwFveHK4trY3EUkxbJQ1soZdpm7ML/7bDN52klaS/EEgwk+FJrNAcm8M+N3kMSZoJyJW7c1OG81d4G84tryt2fa7s2HGT79IX6h4wI0GGu+bl87MgmFC48KdvjPdWowfh2QxkphSLduYQ4ss4EQYgJrmkQznQtt67acCFxNrEyE5psSMQPXtgAbwV94xeqtc+QHzmjHAwICTzk7Q4sFF85cDV54ZyoQDYdfubjpJ6mdE65dftN2eYD/5ywdTq09vRpnlh24PTrp7nn4H+Yddakv5KGhQOnj0p6JHNytXEClmiqxANrsYyhKvZe9gS+5w1RIcrsv9dHr5uL7Q==,iv:PQiVjFf2LlOKa6i7V/DcxYU54m/AbJGwTwUmA9asKI4=,tag:y27R0sMuOno0Al9iD3+MsQ==,type:str]
bots:
    perrencloudbot:
        api-token: ENC[AES256_GCM,data:mbIX/9Kgzfb8ZcyjTD8ltrAGCe471DHh/HeqDpNx8S4XeQWvExTLhKRwsfyKSg==,iv:vqNiR/eS41bpMzgJCMZd+AsM7wo/0UtVjsP2kPUpDAM=,tag:3hRmAlNb//bcmNR2NtQc4A==,type:str]
        chat-ids: ENC[AES256_GCM,data:InyQ3YCCCQH2orsfi2E=,iv:0iAASgJDNg6XrmL+96msW3ubz2CpHMWHEd1Q9kDRFFw=,tag:WLqeFSoictK6SKGOlDR4Iw==,type:str]
backups:
    primary:
        repository: ENC[AES256_GCM,data:qGtrxtrnimS4+Gf5S0VbcTher0eWUiEEYbvdd4W5+WtI,iv:8ptER7muCz/nQryiy+WZVDLhwW+SaLZuaAOYGOQecMc=,tag:+aWH5mi+G2+KF6NOv23KpA==,type:str]
        id: ENC[AES256_GCM,data:wpuHlfgDRSvkAmk12U/msOZcqX4oLcAqBw==,iv:gFGVsyFrxtSekZNorX0YClJ7gpQf7wi5bs2bglHHZRE=,tag:op5IEAL1RulPyfksQa3/jw==,type:str]
        key: ENC[AES256_GCM,data:0R0pyxn/x2UaBwJLfyfICWeE01q3CgeW+UZQoPuKcA==,iv:2Qiy768+KV/+H9wMrUrkTbRYTc71j3KOK/2lslF8g3A=,tag:nW7XzCz0ddAdIva570FS3A==,type:str]
syncthing:
    gui-password: ENC[AES256_GCM,data:RvSw6tBMPUWvV0PQwb4D,iv:S/rxUw00jf0utPzEvtc/sK6EyCOr4Q2GH1VZ8tNkrgU=,tag:8w2ERS1ZcDTZVTRzry1p1A==,type:str]
sops:
    age:
        - recipient: age1xjnkqv32a5nqftw6pqthapnzmgjl4lnqfpxy9utqm56yzm2mvfhqzch648
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnV2pmNWVhTzhOTWcyZHht
            NjB6d1JtNjY2TlRCSlRLNHpja21tV0hYVmpJCkx0M0VzOTVXM09FTStvTVRWVGpw
            Y3hxYmJTR1VpZXRKbFJ6TEszUCtuTWsKLS0tIDRzdGNwc3lFenVlQm1WZlZjVjVE
            a29NajZweXdXekp4K1Q5SmFCbHF3cDgKRdLvQTV2gMnh36FlIr+6Is0d44leyVT9
            N3XzMtsLRP0A0p5ilTTL78dZZERbT7oR6JYBkBvA8BCCI8Kqth/JgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a5aqj3jr3rqpjet9a7y077ak0ymstjjdnyfgn5m2ad4l2yuxr4aqym7d3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1elVCS1g5RkQ4SStPU3ZZ
            TGNZL0liaEFoN2h1KzF6TkdnOHZNbXM1cFQ4CkNOZFhzeUtFak5QbkQvMkxNVVZL
            U09hcW9tWE9vR01ZYitRSlRtakwzMFUKLS0tIFA4djIvYm1PN1JsRkRtcjd0NGli
            OHRRN0l5NkdORjdYUDlZc2s0YkFCTzAK3hadif1qNQSGDRII6N9T/i+QJfxMAJHR
            3VLRnUrtfl+HDDyBQvQJJ3ha5hmXjzkDfEpWwV8B9lBvh2JL3oiCpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g45zy9m5g4e20cjejgd3x40722rlddgkmhtddrl8wyf63kt5kg7s9ke390
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQit2YVo3RzJlUWtqZHRT
            dW5wVmZ6azgzeEF2Q1JZa2FULzYwNzFxWEhvCmYzV2hNNDk1ZlFQcHlFUWtmbjFD
            d1I1YVRFTk5EbWQ3aXh4WjY2b3JaVU0KLS0tIGN0VzhRRjl2TlBZbUtndzNDeS9W
            TTY2OHpUemFNTmVLYnZGeTJicjhPVmcKLzC2RPs2exed9vbU6xYnD6fqEDb6Y1aX
            vxrpc3dH9lp9phDMYqGvnkKMM/rWjzy0PNhG+bnXMRomDBJq5IjnAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ljcy90uwlfngc7vqwlf2x2ckgsdfg90c0r9yvjzpl90jkwf9g48q2leudt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK0ZQTDhoQXB1blBjMU1x
            bXlBTjQ1VlplSTJENzJvWnlRMVdlY0NoRVNNClptV3k3cXZldmVrS1ZNZmFTVVNm
            R3FLSGdpSGJvVVFHRXhSRGdweDJaU1kKLS0tIGZlcEk2ZC9UU0ZmS0tzM2xMZDVm
            eTBIZ2xyaWxONkZTSVp0QjdLR0lvdVEKaTB92YqTYXEbyh7v+mEuqoHBjEQa8VWs
            lL9UnhbMhtyVYxMjJi+VYmcWeObyVQltkCkS9amPzIxYdtp8wpUKpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vl9q7u0jkzjpdqrmg4flvz2f7gyn05luv4ka60hu5l8yn4m6rujquhyc2p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQZkRYeHFSK3Q4NUovT25h
            bmhDa0pUMHFPK3VZQkd5MHNqL3g3SzRsNkRBCjZPa3lmU3JBSjdUZXhpcDl4Sng2
            YUtaV0JiUDZUcW5jQ1pWcjJPYXZndncKLS0tIDBNbC9oSlBaVDRrRVdJc0RDVy83
            dFdGRm9ObGlBcURhckxhZTczZVBFTGMKew15P4VBHXUIh+RdRvn/T3hMOIC0DXFT
            CPKP1MejdXy3FAKsiVPnpRQ7X7bhyxMDtoLLUTdg1Mwh9qmEY+NiZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dxsvz30sv9dvt7l0euu3eq09xs0dlleujyc40fveyxcq4hrfafmqzv4zuz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaDN0NXFUWE5SQXNPNXVm
            SmRrN1dSc1dJNWZpYnl6Q05RbkxMUTBuUmhFCmRjaVh2a2lGbG5YWkdqa0N1ajd6
            b2VPcVhjakltZktrSk1aZjQwNFA5QWcKLS0tIEU1RVpKdzR5aHlrMGtJdkpFT2Jm
            SGt1Z09aR1NESWptNmd4OXdNbUZNcmMKFbT36bExe3dweFOVOE55eofm0duf4T9e
            GANW/tkHkOK2iGre5DIml39MHr/0iPOTPPcdqGm6E40VN6k4d+k0PA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vj0wez5rdsedx9jsqcrh0wjh7tr6hyefvdltp2zapu7q7tfqkg0qez44hz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MndtMURSVUZjZzh4akF5
            cHdiYWlHME1KRVE2TmNKSkl6ZFJqOENmVlZ3CkdsQW5ScUtWUFdnRlQzN3hDNUYw
            K0JtdUtDUUx3UUk3YnV2U0E2ZkJoNWMKLS0tIGRvN2FxamxmQUV0WEI1eENHd1FI
            cncxRTRwMHFhdEtJM2N1WlVNVE5lNFkKhfz+J8EAQCGKgEP3pxs3tqmJ97XxtwOe
            hiSwvZBMMW6uz1Af+7DiA6rb9hT24lGPwHktRp88nyWUOIFqnsyVgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1649y4antwgfe4fu02eppnx5gr0yc3g4lj4kwd6v9guxgxgj06y9qk7l4wl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUjNRMUtwT01wRzd5d0c4
            eWdFRmdyZSt2eUFNRVFsbjNrYUx5UFZIZ25JCnB1eGJqNTdqR3FYc3lyQ3R5aUxQ
            a2hZNjY5ZEJCY1d4MmtLVXlGM2ZQL28KLS0tIGxGbDcrTFpUQWo3cEJ5VGgrME1l
            bWQ3MTlDUHJmeVNVdEthcjh0TEE4K28KiGf4YElDKQLFuy26yf+8ogz2kmgzgfdC
            ysCGA3tQ82OnjmTCNNzWyrVnCqO77p9y7k7OGKeGPcNoBnUzAKxlHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k085uuy4fv9rfpy0ne6zl9fq0j05a4fykqe26psx2ngxqrcxcu5sksxa9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOUdNeHp3c2xvclFCc1hW
            Ui9rNUdjR0twSDIxRU5QMVowOUQ2UjQrakZzCmF5T3QyMWc0R2I5SU1URGw0TGts
            MjVBZ00xUTZObC9vVmNzS3lvaDhJS28KLS0tIFhFOVI3QU4yeWRCTC9zVjdNYzJZ
            clROWlBvNjR2MXVNRkFuQ0hNQURnb28KStpUvERx3KhevhSeM5zXbqYgF5ORxE/E
            OewSUriJ0Kz49WuJFnRa+xtrFk8delgeoGRQBYAvurZdLe5BzcsnXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tpeqfhc4n7swpgzx6qfdfxanx0uqh7nksr7eksnvjea70n8vaf5sntxu2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZGJRanI3V3V3dlZ1ZVpN
            NFRwYWhHY0ZIaGdhU0U1c1lwTkplRHVrT0NNCituVFpyeU80ZTBsMkl2SlNCbXBP
            MllXV0JHMDd5ZjNGQklQUmM1eXJqNUEKLS0tIEJDMnJicEl4am9xdVNJRnJCNVhL
            Y3A0YjdESEhNTGQ0OERMVE5DQVRoQlkKLpOXujXiLd5TBvA8XbhTFtq7oE1J4EPZ
            MwtbWHafyhZUhtYnFDKYy4R8TICSwgSplrAQZCHG+fjwJGB8fx2dEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pux20jlyzdexztdmm3lelzn2mslxhuahae4wjy74hkxfytslsfpqj708e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OUw3V2JGYVhCQ3JJelFJ
            dEJ0Mk8wcVVBa0xwUk91ZHcydHVsd2ZwZ1VVCjVLd0JwL0JIUjBwcjRDTWY4bERN
            TEU0WXZpUFVzYk1sUGc1bVB1L0dxRncKLS0tIFpBc2FIWVhwV1A1Mlh6K2pZNmNM
            Ym1pNm5heFg0bmpkbURDQUlkQ3NLQXcKQCiWTwyXrl8VeBQoqdTXSS+yiRYjlZiP
            n3uQCk3j9AJuEGotSaNhD241LF9/JkZL9titJKESi4xRkmROQk2rtA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f5039syajzz75s9lkdzwnv2dsvlcp69puuaucgwt05sqjdl7hels25nsfr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeEsyVUc2dDVkOHJwdUdi
            WmNoS3RCejRKTzFrNUoveUY0QlFXVjJJR1JBClVoNldBWGxiUDBmQlNvVmJyMHd0
            UDFwSkh4OG1sNnFUUHR5N1FSQWJnS00KLS0tIG9BdFJUMmZEVS93a0xtWXRnOVI5
            M0xuWStPRG9WdFRveWJpdE9GbUlrNTQKkHkS/eKjICJYLmFhQBVVTZGCEhtGz5Nb
            ojRqqGHR3RHw9Mx/HomE4Lk5LLKq90O/PLJQFNT62FZgk5PfwFeCBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19m6f3xtkdf3gwxqxgp9w9gyla4hk24f85l2tyjx6dxu0akzux3cs657dhz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eGRXeUkybzFmOUtFTEdG
            SXpCWUZEZTAwTGF3dGsrS2lVMnVJRFkvOEU0CkZHL0VQRldCL0lGVVJDbFoyNHo0
            MUNlblgxN1RiUWt5elMwUm5iR2F1RUEKLS0tIEFic0RDbEdnV1BQK3RyZnIvZ2to
            QmpKRXNNa1FhU2hqYXVncitubUppeU0KIuYb/fEayx5HAjqvzdljgXo6anldV0el
            XEOIZqpkz/OfgBjjFPBr4D1LnMjV2MYrbqO7ghxHS0dgl9a5GRiCoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1en6vdtxspam9s3nmsyfrcrxzrzu4t9v72ztqyekpzsc35rd06a2sza7ehw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1M1BNU1BEM0IxNEFxYUMz
            UWZKWTRWZGZSeVgyVm1kQ3dCQTVSdi9YNTNVCjZMa0pyMTNwNXZ3YzZpWlU0UDB2
            dG9HNlJEOEVOdmp0OVBWVXRheHIwNlkKLS0tIE5xNGRObzYvRkVXYlF1a2RyVGp5
            V3BjTG5XbDBueDNIR05vUTRZb1QyQ0UKIJ1U9y1O4ys/S4jbUS3pcwH+aIwpJfc2
            jJiXVkKicWIfUrBRs88L7xHUSwea0MqkZ4Hv1PJa4uZQ54MLXYODCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vujvq5rdzppkkdhkwyhnl6xhuvm8s5yf2wc8ke05m8jwrdwsdf0qfx5w4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYmpNYnFkRWpiYUdibmF4
            U3ROQTRmWjBFRVlNakU5UnpROWNsOXpUdmhRCmhqMnpMMzR2TUhoVXFNN1pQNklT
            VWVDVE9Vclg2K001THIzOGkzNVQxeEkKLS0tIGVQSFc4akVmdUN3Nng5VHpjYmRB
            aCt6TjVWUkRPc1dLYUc1amc0bjlhVUUKzjt6Oaxc3agD0ziwjd0hZ8JgIeE59DMC
            4psne5yrC9nFFL93cMivor6iATXpaVP/jJKQHRBChOo0XNxFmUEJZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uyuudfya8etgztlt6hlssr9hkstyyhg65wdq3pj9rud2czzkaqqssg7yvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTjAvbGZZb2ZocHJFamZW
            YktOMHViZWNWakc2aVJSdHpxRWpTYkp4blhrClgwcGhsYVBNSWN6VXJZcGo4djZ5
            RzQ3cGVyL3ZIeWFyMjJtU2hHTHdrMk0KLS0tIEpJNUxVNXdjUGlHZmNzL3hhbGVO
            NHJKMDJybXIwMUNSNXFBbGVlbzNoRDQKL0zp9/Fs/8pG3/O62lYbPrwrW+O63wWD
            d91vtAwjyBHlzsWMsjkI4Qm9dmU+D7WXh4mfL2SzNYpEkX2/9YFU3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hu2jmgzzpjmc8nhpgfslsqma05l8n445sk28f8z5dqu5nr0e3pmqt5f8yw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKMXdwSjFqeEk0RFRzcUJH
            NmV3QlhuK3c5aFFpc3RIdDEzL0pMek1lblQwCm9QbjM1bC9qK3NpYUdsemoxSDdK
            eFBZYk9Vb0RsS0hON3J4VThJcEhZdE0KLS0tIGpUQWtnVFV0aXR6UkE4QUJndWox
            R3hoY2hhU2lRclEyMVNjY3hHeXpLWjAKG0sHL626PR5gS7Y8duixUuYVP4WzVYH3
            sUbKKsbT8E1VlRDhZrwGT2rwMGuEQ1fqbtYqWAuLXc5W6p/P8Cnc/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17k70g4yrrkcuzshwefpx0ll3hp9nyytfcgrfd4cv3wxvn0g60uusw4njfj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdEZLcm82djk2V3VVc2tC
            Zkd6Yit2eVBDTjIreWsvdWh3clRUZkV5bndVCjh3VzMxNjBoaE00T0dXenNsbFFQ
            SUsxeWU2b25ydlJaSjJ4UXJFaE5LSWcKLS0tIFpuOUlDcXovYndVVXhVZWZ1UmNa
            eUhNcGJEbE9PdG9GeGRXT2x5cTZscm8KgGwSBT8CrGiT0FrvqLJmVW0lf0hPd6A3
            vVNn/BREToy5SABAz32plLIvf9uIpGRJ/aEYbdLIT+/ITErgdlolTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T06:45:38Z"
    mac: ENC[AES256_GCM,data:XMFW/JJpI1DyBvtEIzNhsiHBaVzbcjspUFkBu6L5Bfqns1UV3nwM/ftxwb3pseoFx9+MPUHT1rjAI9IU+AhtEJx23A1m116vnybLaDngxf9br0lJm4u+JzboeUr6ndaGoZFYEwD175CHx5yo74xZ1g4Sa6dyKcjT1wZM/CJmyhE=,iv:7dMkDgF/Qo7yj1LbCHaUbShZtD2HMMlJ2xDN48vlw70=,tag:0qgxL+0K91XZ+KSqagaBYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
