accounts:
    root:
        hashed-password: ENC[AES256_GCM,data:WmZVlgKuhhr0giWDRmvGxanJb2xHC/mCZJ4w/g/bGVjUD26rcFAC+gSJXJd0k8OMzfQG1heW/ugpVoNLze7T9SyC3EmxeOUXVQ==,iv:okbRYi3vm1CesnO01QMWOuGMw9r1wTzUoJv68pcNZHQ=,tag:XtIDWn9XqLWf3iJmFns+Ew==,type:str]
    caperren:
        hashed-password: ENC[AES256_GCM,data:8pLgyZScZIi/gia0TQskZ0gnYboNbar73MPgTWQfKweEyUI8NotJfI/v6kXvGq2l41qAPhmjFyij5uOzYTwANpd+lonvSY4zog==,iv:cva/YYDULMuM/QoTiC/7BjVUs6nAy6+4gL9XenTWDAw=,tag:F66PTiXlnfx05rIW11EEvA==,type:str]
ssh:
    ilouser:
        id_rsa: ENC[AES256_GCM,data:BuoM1E1pf9srSfWWV+bIy9H/JAQIMsucJv8T+Sky6HgSsR1WLdOX8pYJSVukuMMisSBG8DJiGy7PgzqeZohrFbkaHpc7gI0S3+803pZQjILzs9kEIrpTzqb+i5UgGPNn7Q9Rk2Etm7UlQAaUSLZg1XfCWV421YeTDFnM42bLy8Lhpb5J/GyP4iYJN5osmlQdjUbzR4wWaYIofWHjTqbNo0yNdMTDPf/bVDw+/34Xx/Xcvc90KtbO/k/gWpOam/Mq/jMoaA0IcZu7p6pu3WWFlilkeBtLefLo8nDEGi13hT2KxrB89npTNWWXf4sejQxkZgp8x1FxA8LH9v6vRunvdBRNTw/JjmtxaF8vKfjd2oxaKztLA8NROYQRpavqv6/NGlyBCU+yncq/E5dl51t7BwDwpSUvYvVEP20qH1JBKtiyuHlLOTOwTJtigOE3EuNxuEViz56Q0tVpQOcPQuSRmwdOg8hMZx/HnaDv52JVxeQHdF8jpzz3E3noB1AbRIAb84XXWVo2QLxFb8W8t5ta5cdOq/Pqte5PNXfT+2pjBIOlfg5mzA9kjH4QOZaO7zBbMj/ZD480gZY+kUMgeXgOtoLSZCPvdBbSjd7Lsd7xYbZSk6m4jOtvbTzpaFX8ZIT4ompC/+G84t3HyxE+UUeBip7mTeOJBCc1WjguKSzdBMmYZUxJAGMmWJ+TQDZSFu2m7bMmLGTgya5isqtcqGN5cGcICxIfOVfuoJ5T6vO3t2ZdUuV2U4+gfCYhtEZbsT/lhgRC0NlMWBhowCRpzhowYLHHGqmUfl5M+JTCAOS1QDmZvaGVc8BC0WWkc+162NGME1D+GRolHF44TfB5IuTQ1cfrv+VvK4DIsEslleAMCxqHPPQPGpCTcCNfe/3Yylkl/Pmogas2P8Q1fyGVTZCsS2G5wugptt8AdfdM+tvmqzlyponw3lNKe+mj1ehunJ8V93ea95cdmVikM6OLykzSrbxsejX8EgIQ0BChAFly38ot7YcmqgfqABCGeiYwOnL/90EuRmYRaMuUihbiRVzGPd5oc0OKDj5xdM2Eq/VRaODCFuhmwK5eLHB3tGab2Bin/8VGZkpWjQsd3H/UYRfPpJqjnhI3/dxD619ouZPfsTfQCVnBaZMYVKzpmeb3geNMeV1h8cDxNsAk85nAnG6RUF7xlqmgF6yUZ/vFtjUq/vCoNHsKvS5sSy73LPXljrVvZyG2K9P6dfTR4n8yYGJCoj95ahCAD4djsr9ylRzj1YTFQ7XdZGxw3GML7rmzuMS/Kk0qMKNYSlS9ru0yIL2baZmntjUKjcl0qigzO74bi3TxyoylmxXA2/80AcRU/fWi0t9g9aTJmuVztPiRQpCLsDzSS/xTjriwThx6v7tgmVwO05SdlBQ5Fk6R1nOsC+4X35l2f6pWJ91nlkfimJM3mY/MZDxWusfgXcS3SBswj59n7zX7AwykcX6/XHVWg91EfB6sRUZyHWsMxwn+i/P5aoIiO43leCD9KX5T0KjRAxa0DG092zM6pRaKEJWeBXTgcFTS5AQdMLVlt5GBHBHw2Slr6SMsUo7A1ycJqP7nw+YdLje86h4edfvbAtowhaBT3WPFoxbtAoBWqkYPgTGs/AiKRsfjecypuCm52bz8VTiw8laRkYFO0nqyYZBm4u2BbVODS6Ji9ZxNpjN/NIDh/5ffhQ611iwL2xgob/yFrjqaRyzPx1DXseMO+Lc0TMEhdSVGG9i8fTJXN8VasDDHxWCQD/ZSyERGCqIDc1+pZBjwABiECsDtQy3DI+oQ3UEPLOFHGS95Kc5+KKij3ptvf61o2J6XKEUY0jqv+puNvmjz7jqsNBY+S524G+06zzcvXsUnWQ3o1lOseFDSl4ZV+a2GiRA+AHj5gSKXTNVUMDsEu7E+4Sg1WVFKLw4KgZ0KubHYQYz56QLojv2TUL3NrK1mUfdn9jeJ01L+CIMTVjz+4UjVI/AZJA370Le01pl0ZMxaFRa0fep1Pa6MikTS7SO8NBtTtbOI2Dt/hBrXpzbicfRU/2pNJ8hEn9in0eXkZ3h0/nHm5J/OrrbVOdvQK9RkF9J0sdgmLtnAxdQjKK7r8Tg17q4vefFRtTEFPz1hV8sOrNXJZc3GRnvINE/7CVYdBQZuq7Bqze9WS+Yqzo2Z7T+cgpLTThBWlL7uGRsNcOdxQOctvoHCDFMV+9+QSH9Cc55Jdbd1T/clludubmyCJLvd5+25haXtRNSivJ/qB/ZbaZq/1PrJw2rl9XuiTczVrG/5Gwpz7a7PVrP8ydIEoTAglMdr9WICKl2cqHo1+k7HOFZluJAugNTV5aRwCvb6roKXsENH6TE68RuiYI8GXD/AzrY86TADCZroeQ+arLW+UuDqQfsnJ6MM02NcSOriAqTbwikGSzNIwkOiuZmwc5Y1pVqe1pyVDf5gN6Q=,iv:IDe6vkBvgAzfxee+/odkLk1TLZRghVEf8hqH2r3+V9I=,tag:OFCA57fQjQxc+CT9DOq+VA==,type:str]
        id_rsa_pub: ENC[AES256_GCM,data:hYdf7KifFqkHDa8UF1zvhirc2AkrYpL2VrmV2IJjHzzgbrJxshdA629mTXwXwXORbLwNcMpRR7DFLyHCRDu5cWsxluZ04rNU9sJFmL+6pPUonaa4Wc+9z5VysV8UItY/BZ/5mOMQ2ph/wMQ3pkFnBD58vOFOYsmZ7OCir5dQZfm8GdGDX76bOlOI/CAg/LtwFveHK4trY3EUkxbJQ1soZdpm7ML/7bDN52klaS/EEgwk+FJrNAcm8M+N3kMSZoJyJW7c1OG81d4G84tryt2fa7s2HGT79IX6h4wI0GGu+bl87MgmFC48KdvjPdWowfh2QxkphSLduYQ4ss4EQYgJrmkQznQtt67acCFxNrEyE5psSMQPXtgAbwV94xeqtc+QHzmjHAwICTzk7Q4sFF85cDV54ZyoQDYdfubjpJ6mdE65dftN2eYD/5ywdTq09vRpnlh24PTrp7nn4H+Yddakv5KGhQOnj0p6JHNytXEClmiqxANrsYyhKvZe9gS+5w1RIcrsv9dHr5uL7Q==,iv:PQiVjFf2LlOKa6i7V/DcxYU54m/AbJGwTwUmA9asKI4=,tag:y27R0sMuOno0Al9iD3+MsQ==,type:str]
bots:
    perrencloudbot:
        api-token: ENC[AES256_GCM,data:mbIX/9Kgzfb8ZcyjTD8ltrAGCe471DHh/HeqDpNx8S4XeQWvExTLhKRwsfyKSg==,iv:vqNiR/eS41bpMzgJCMZd+AsM7wo/0UtVjsP2kPUpDAM=,tag:3hRmAlNb//bcmNR2NtQc4A==,type:str]
        chat-ids: ENC[AES256_GCM,data:InyQ3YCCCQH2orsfi2E=,iv:0iAASgJDNg6XrmL+96msW3ubz2CpHMWHEd1Q9kDRFFw=,tag:WLqeFSoictK6SKGOlDR4Iw==,type:str]
backups:
    primary:
        repository: ENC[AES256_GCM,data:qGtrxtrnimS4+Gf5S0VbcTher0eWUiEEYbvdd4W5+WtI,iv:8ptER7muCz/nQryiy+WZVDLhwW+SaLZuaAOYGOQecMc=,tag:+aWH5mi+G2+KF6NOv23KpA==,type:str]
        id: ENC[AES256_GCM,data:wpuHlfgDRSvkAmk12U/msOZcqX4oLcAqBw==,iv:gFGVsyFrxtSekZNorX0YClJ7gpQf7wi5bs2bglHHZRE=,tag:op5IEAL1RulPyfksQa3/jw==,type:str]
        key: ENC[AES256_GCM,data:0R0pyxn/x2UaBwJLfyfICWeE01q3CgeW+UZQoPuKcA==,iv:2Qiy768+KV/+H9wMrUrkTbRYTc71j3KOK/2lslF8g3A=,tag:nW7XzCz0ddAdIva570FS3A==,type:str]
syncthing:
    gui-password: ENC[AES256_GCM,data:RvSw6tBMPUWvV0PQwb4D,iv:S/rxUw00jf0utPzEvtc/sK6EyCOr4Q2GH1VZ8tNkrgU=,tag:8w2ERS1ZcDTZVTRzry1p1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SXdSSnVGbGtqZFBTbGtt
            aWlSaS9GaDVhZkZNQ29vd2d4dVFJSlVOL1ZNCmt3TjVQU0dvVG9TOUxQWXlTZno0
            b1BuQS9USlROZ0szQTZzZDhNdFh6SjAKLS0tIGdIQXhvT0RsSlgybUV5bkFRTVFY
            S2dQNGlOME5OWGdnYjY2RkpUL21melEKgr25ZDS+jiAS2o9rXmNvL2u0WCKU9QI7
            /qZmIJa7Gh26Eh8GKVeIUNron+WvRuDBhcFRb4QNKqym4zJKtMeS3A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xjnkqv32a5nqftw6pqthapnzmgjl4lnqfpxy9utqm56yzm2mvfhqzch648
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQUdXYzRjT0N4UzVIWW1O
            OGY2VXRBV29DTHJTandVZkRjVVIrS1QzajBnCjBDU052NUROSFloV3oyWVhZaUVT
            U3F5eDBvdisrNnhhTVBwMndzNGZrcEkKLS0tIHpCM1lGWVplUUpaZ1ZpQzhTU0Jt
            aHBReWVvV214Y3FZcGd1Wk5BRFBLd1kKGLuzsHGkror/+3quuCEt0EtSExp88EEA
            uCRP729xKANI/rSgoehQuw4ssIFnM8TS+G6TpJjUucsDVivCtyjwHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a5aqj3jr3rqpjet9a7y077ak0ymstjjdnyfgn5m2ad4l2yuxr4aqym7d3d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VzhCdXVXVEpYamZrK1JR
            aUVoMG4rT3hYYi9NVy8yOHNWWXJhcUdhdVVBClp0QjJtV3preTU1SmhpWnJQOUhF
            ZHU1VVBZb1RrWlVpdXdUTS84Vkl2N2sKLS0tIGd3ZHpaaW9pUXJuOGtNYXV5NTFm
            WlFrOVJrNTAvelZ4MytIQ1A0WnJJQ1EKLDRuHT6DU1la67IKUmpQpH+kTU94uCkA
            5XlIVB9haZWJGRkNOzp4PNVnjszjs0sX6knXZB2ryoMtx2ubueSBvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g45zy9m5g4e20cjejgd3x40722rlddgkmhtddrl8wyf63kt5kg7s9ke390
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ1R3THdYUDhZTGM3bG9I
            ckpwYWp4RkxaV1JvUnpTRnQ0aHJ5R3lpaGhzCmVLY2NWQ0NZTmc0dCtLakdGZEJ6
            OEJ5cFBaTzZlTmk5alovOW82NnRVSGcKLS0tIGZYeTBqcFFXVFBRVlBJdEJnWnhu
            RWRKaVNFc3h4TVNHWHZGZTNQd0d5UkUKujpvMwjjU8ezVPOK/pWo2yY6JZxoqyBk
            8x/iFXilgsttA9P3lk8sR9zpmqaBn7AZYHsMoqRLmrW1MfLc+B6I9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ljcy90uwlfngc7vqwlf2x2ckgsdfg90c0r9yvjzpl90jkwf9g48q2leudt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKT1RENExRUXBaNzRYTUkr
            VVpxaFNUa3BBMFBudzVNSnNmM1M3OXNOV0NFCjVnZDYvOHQ5ZnJBT0dTUkF1RERz
            eHdEUkI4K2txanpyQ1E3UVNYeDg5QzQKLS0tIGFXNjBzNjhyNTlySVZXUEJnVWdv
            QytwZ2ZKVytTUTdrcmdkR3dFMWdCMGcKK8Cm5zU8BtBEmpPMXqiJ9tRT+MZIMB5y
            NOcIJfsTKltmO2KGNutrLtGqzTmwMMILiTeIkM2+I5LJOLgyNWh67A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl9q7u0jkzjpdqrmg4flvz2f7gyn05luv4ka60hu5l8yn4m6rujquhyc2p
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU1JKUmxUdlo4UXd2Uk8w
            SDNBOGpiMDkxbEduaVRWMXRTSUp1eGJ0bkNzCndTREVJT25lU2Y4TkxNTTRhc05j
            cWg3c3VncG0zaitMYkpwRnJWVWJZZEkKLS0tIFcrUWE1UlVWZUVrdW1ZL0c4bG5P
            RUhQa0Ywd3VIbkNKa2dlTWQ5WHhlUUkKy5m8KZfBNcrC8us+gEUiC8LIceETjdie
            4wlyaeIhaYRAKGSknNw/3+XVOKKIPDd516p7vWkj6BBmFn72IBKcnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxsvz30sv9dvt7l0euu3eq09xs0dlleujyc40fveyxcq4hrfafmqzv4zuz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTHNRZ2dJbkJDTmxuWjdk
            MTUzRnMwT3VMUnZmYmVaano3K3cwUHZwZm1BClpvUkgvdjJTNVNYY2hIOVhHRlNF
            Y0hyMUxSbFlSaXFTcHpjNkZManV5MEEKLS0tIDM4VTRHSWYrMkF3M1BCNndKVXVE
            UEMvTGtkQUU1SElubis1MldxS1FZSncKFqKUXN2QiDMeOTBJDVxZZsm7fXEvokBT
            elKyfCrIXWE16xPm+ICSfbkd2GkE2jjseahdskWLJQNfIb9JdtRvTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vj0wez5rdsedx9jsqcrh0wjh7tr6hyefvdltp2zapu7q7tfqkg0qez44hz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S0QyOHBtNzVlV21CbDZK
            VFd2YUYwWFRyZ3NrcTBWZVlpZjBMb1E3ZTBBCkEyTzdYNDNtQ2JuZkFsaXBlUWsv
            aVVORExDVzR2a2FIeDNKcUZ2V2c2RTQKLS0tIGREVUsrbEYwZVZ6RDRsVWJaQnB5
            dnRIVUtXRkx5YWlOdE9neW1WWjROdWMKo86rKe3XRubzarRDjLnBdv646rIezFXV
            sDNVfhTaZKRM0byVF2+mIqgVwunagzP0XYoIgYr79H5rnaTfttaVsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hu2jmgzzpjmc8nhpgfslsqma05l8n445sk28f8z5dqu5nr0e3pmqt5f8yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MnBhMXM0eGRjSUxwejRq
            L3RyTmU4TkgzZStJeEUyUHdzSjVpcHNvZWtjCm5DaHVSK2haSFlWc3NjUkdFTENu
            Q0VjWkZWNVlJVUF2cXNMWXNaTzRVMEkKLS0tIGVMY3pZS2xXbUZaTHVhWHh2QmVH
            Q1FQUm1WY2dPOUdDK1NCVU9LSnNlK00KZYp5IHrx7m4KRqRB0e4FDihjudPQSrLL
            cwLRjZZYezByWGRJFPw3aZcfhPJv7z33lGuzWyyQ7Dciyp2x0deEMw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ldrn70e09s99p0frlkpywpns0sl6vr4y4kdxr9r47wuh9swq2faq30au2h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6V0lxU3hWbGxCODVKNC8x
            dm5rTjMyU2JmY1E1djV6Umt1RG42UVFvV0hzCkdMRzhxcWk2WFI4Qk41dWV6Mkdi
            NStsaVdVUmFDcmlhY2tMUmpnc05saFkKLS0tIG14c0wxNW9iOTYvcmZGVnNaQWQv
            QXlsWU04UmYxTzlUcU0xM2xFVDVVV3MKdb3SZZL8MBSFsubkhhrJsd19yYzqu43f
            Mkxytzz9RoEDjOpE+SEwff22DJSE+fBu2cN6Gy44Jc4sTDGmLhwNsg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17k70g4yrrkcuzshwefpx0ll3hp9nyytfcgrfd4cv3wxvn0g60uusw4njfj
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQVZNNDdEQmJvMVJsV3l4
            b0VEY29DM2xZTWRiZlk4c2tBM0dBZDhkWXk0CjlFNWQzcjZ0S2MyakR5VEY3Sms5
            VlkvMnh5VlNlK0NoN2FITEt4U09BNDgKLS0tIDc1QUhHa0JITXl5T1doNk9wbTRU
            cGRiSzdsUzFEalVhcHZNWTBtYjZ2bEEKBnyT3QVdPvS2ztBKoQDjw3VCKQzu6H2S
            toztSu0RRYweP3pKm5yBP45Jay14yNnU6ZPdqVmzKSfWzooXLOfUQg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1v0l0vem97plxsnj9m7xryrevmahfcqvfygfnm2p0vzk64jkalvwqw4zvvh
    lastmodified: "2026-02-06T06:45:38Z"
    mac: ENC[AES256_GCM,data:XMFW/JJpI1DyBvtEIzNhsiHBaVzbcjspUFkBu6L5Bfqns1UV3nwM/ftxwb3pseoFx9+MPUHT1rjAI9IU+AhtEJx23A1m116vnybLaDngxf9br0lJm4u+JzboeUr6ndaGoZFYEwD175CHx5yo74xZ1g4Sa6dyKcjT1wZM/CJmyhE=,iv:7dMkDgF/Qo7yj1LbCHaUbShZtD2HMMlJ2xDN48vlw70=,tag:0qgxL+0K91XZ+KSqagaBYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
