accounts:
    root:
        hashed-password: ENC[AES256_GCM,data:WmZVlgKuhhr0giWDRmvGxanJb2xHC/mCZJ4w/g/bGVjUD26rcFAC+gSJXJd0k8OMzfQG1heW/ugpVoNLze7T9SyC3EmxeOUXVQ==,iv:okbRYi3vm1CesnO01QMWOuGMw9r1wTzUoJv68pcNZHQ=,tag:XtIDWn9XqLWf3iJmFns+Ew==,type:str]
    caperren:
        hashed-password: ENC[AES256_GCM,data:8pLgyZScZIi/gia0TQskZ0gnYboNbar73MPgTWQfKweEyUI8NotJfI/v6kXvGq2l41qAPhmjFyij5uOzYTwANpd+lonvSY4zog==,iv:cva/YYDULMuM/QoTiC/7BjVUs6nAy6+4gL9XenTWDAw=,tag:F66PTiXlnfx05rIW11EEvA==,type:str]
ssh:
    ilouser:
        id_rsa: ENC[AES256_GCM,data:BuoM1E1pf9srSfWWV+bIy9H/JAQIMsucJv8T+Sky6HgSsR1WLdOX8pYJSVukuMMisSBG8DJiGy7PgzqeZohrFbkaHpc7gI0S3+803pZQjILzs9kEIrpTzqb+i5UgGPNn7Q9Rk2Etm7UlQAaUSLZg1XfCWV421YeTDFnM42bLy8Lhpb5J/GyP4iYJN5osmlQdjUbzR4wWaYIofWHjTqbNo0yNdMTDPf/bVDw+/34Xx/Xcvc90KtbO/k/gWpOam/Mq/jMoaA0IcZu7p6pu3WWFlilkeBtLefLo8nDEGi13hT2KxrB89npTNWWXf4sejQxkZgp8x1FxA8LH9v6vRunvdBRNTw/JjmtxaF8vKfjd2oxaKztLA8NROYQRpavqv6/NGlyBCU+yncq/E5dl51t7BwDwpSUvYvVEP20qH1JBKtiyuHlLOTOwTJtigOE3EuNxuEViz56Q0tVpQOcPQuSRmwdOg8hMZx/HnaDv52JVxeQHdF8jpzz3E3noB1AbRIAb84XXWVo2QLxFb8W8t5ta5cdOq/Pqte5PNXfT+2pjBIOlfg5mzA9kjH4QOZaO7zBbMj/ZD480gZY+kUMgeXgOtoLSZCPvdBbSjd7Lsd7xYbZSk6m4jOtvbTzpaFX8ZIT4ompC/+G84t3HyxE+UUeBip7mTeOJBCc1WjguKSzdBMmYZUxJAGMmWJ+TQDZSFu2m7bMmLGTgya5isqtcqGN5cGcICxIfOVfuoJ5T6vO3t2ZdUuV2U4+gfCYhtEZbsT/lhgRC0NlMWBhowCRpzhowYLHHGqmUfl5M+JTCAOS1QDmZvaGVc8BC0WWkc+162NGME1D+GRolHF44TfB5IuTQ1cfrv+VvK4DIsEslleAMCxqHPPQPGpCTcCNfe/3Yylkl/Pmogas2P8Q1fyGVTZCsS2G5wugptt8AdfdM+tvmqzlyponw3lNKe+mj1ehunJ8V93ea95cdmVikM6OLykzSrbxsejX8EgIQ0BChAFly38ot7YcmqgfqABCGeiYwOnL/90EuRmYRaMuUihbiRVzGPd5oc0OKDj5xdM2Eq/VRaODCFuhmwK5eLHB3tGab2Bin/8VGZkpWjQsd3H/UYRfPpJqjnhI3/dxD619ouZPfsTfQCVnBaZMYVKzpmeb3geNMeV1h8cDxNsAk85nAnG6RUF7xlqmgF6yUZ/vFtjUq/vCoNHsKvS5sSy73LPXljrVvZyG2K9P6dfTR4n8yYGJCoj95ahCAD4djsr9ylRzj1YTFQ7XdZGxw3GML7rmzuMS/Kk0qMKNYSlS9ru0yIL2baZmntjUKjcl0qigzO74bi3TxyoylmxXA2/80AcRU/fWi0t9g9aTJmuVztPiRQpCLsDzSS/xTjriwThx6v7tgmVwO05SdlBQ5Fk6R1nOsC+4X35l2f6pWJ91nlkfimJM3mY/MZDxWusfgXcS3SBswj59n7zX7AwykcX6/XHVWg91EfB6sRUZyHWsMxwn+i/P5aoIiO43leCD9KX5T0KjRAxa0DG092zM6pRaKEJWeBXTgcFTS5AQdMLVlt5GBHBHw2Slr6SMsUo7A1ycJqP7nw+YdLje86h4edfvbAtowhaBT3WPFoxbtAoBWqkYPgTGs/AiKRsfjecypuCm52bz8VTiw8laRkYFO0nqyYZBm4u2BbVODS6Ji9ZxNpjN/NIDh/5ffhQ611iwL2xgob/yFrjqaRyzPx1DXseMO+Lc0TMEhdSVGG9i8fTJXN8VasDDHxWCQD/ZSyERGCqIDc1+pZBjwABiECsDtQy3DI+oQ3UEPLOFHGS95Kc5+KKij3ptvf61o2J6XKEUY0jqv+puNvmjz7jqsNBY+S524G+06zzcvXsUnWQ3o1lOseFDSl4ZV+a2GiRA+AHj5gSKXTNVUMDsEu7E+4Sg1WVFKLw4KgZ0KubHYQYz56QLojv2TUL3NrK1mUfdn9jeJ01L+CIMTVjz+4UjVI/AZJA370Le01pl0ZMxaFRa0fep1Pa6MikTS7SO8NBtTtbOI2Dt/hBrXpzbicfRU/2pNJ8hEn9in0eXkZ3h0/nHm5J/OrrbVOdvQK9RkF9J0sdgmLtnAxdQjKK7r8Tg17q4vefFRtTEFPz1hV8sOrNXJZc3GRnvINE/7CVYdBQZuq7Bqze9WS+Yqzo2Z7T+cgpLTThBWlL7uGRsNcOdxQOctvoHCDFMV+9+QSH9Cc55Jdbd1T/clludubmyCJLvd5+25haXtRNSivJ/qB/ZbaZq/1PrJw2rl9XuiTczVrG/5Gwpz7a7PVrP8ydIEoTAglMdr9WICKl2cqHo1+k7HOFZluJAugNTV5aRwCvb6roKXsENH6TE68RuiYI8GXD/AzrY86TADCZroeQ+arLW+UuDqQfsnJ6MM02NcSOriAqTbwikGSzNIwkOiuZmwc5Y1pVqe1pyVDf5gN6Q=,iv:IDe6vkBvgAzfxee+/odkLk1TLZRghVEf8hqH2r3+V9I=,tag:OFCA57fQjQxc+CT9DOq+VA==,type:str]
        id_rsa_pub: ENC[AES256_GCM,data:hYdf7KifFqkHDa8UF1zvhirc2AkrYpL2VrmV2IJjHzzgbrJxshdA629mTXwXwXORbLwNcMpRR7DFLyHCRDu5cWsxluZ04rNU9sJFmL+6pPUonaa4Wc+9z5VysV8UItY/BZ/5mOMQ2ph/wMQ3pkFnBD58vOFOYsmZ7OCir5dQZfm8GdGDX76bOlOI/CAg/LtwFveHK4trY3EUkxbJQ1soZdpm7ML/7bDN52klaS/EEgwk+FJrNAcm8M+N3kMSZoJyJW7c1OG81d4G84tryt2fa7s2HGT79IX6h4wI0GGu+bl87MgmFC48KdvjPdWowfh2QxkphSLduYQ4ss4EQYgJrmkQznQtt67acCFxNrEyE5psSMQPXtgAbwV94xeqtc+QHzmjHAwICTzk7Q4sFF85cDV54ZyoQDYdfubjpJ6mdE65dftN2eYD/5ywdTq09vRpnlh24PTrp7nn4H+Yddakv5KGhQOnj0p6JHNytXEClmiqxANrsYyhKvZe9gS+5w1RIcrsv9dHr5uL7Q==,iv:PQiVjFf2LlOKa6i7V/DcxYU54m/AbJGwTwUmA9asKI4=,tag:y27R0sMuOno0Al9iD3+MsQ==,type:str]
bots:
    perrencloudbot:
        api-token: ENC[AES256_GCM,data:mbIX/9Kgzfb8ZcyjTD8ltrAGCe471DHh/HeqDpNx8S4XeQWvExTLhKRwsfyKSg==,iv:vqNiR/eS41bpMzgJCMZd+AsM7wo/0UtVjsP2kPUpDAM=,tag:3hRmAlNb//bcmNR2NtQc4A==,type:str]
        chat-ids: ENC[AES256_GCM,data:InyQ3YCCCQH2orsfi2E=,iv:0iAASgJDNg6XrmL+96msW3ubz2CpHMWHEd1Q9kDRFFw=,tag:WLqeFSoictK6SKGOlDR4Iw==,type:str]
backups:
    primary:
        repository: ENC[AES256_GCM,data:qGtrxtrnimS4+Gf5S0VbcTher0eWUiEEYbvdd4W5+WtI,iv:8ptER7muCz/nQryiy+WZVDLhwW+SaLZuaAOYGOQecMc=,tag:+aWH5mi+G2+KF6NOv23KpA==,type:str]
        id: ENC[AES256_GCM,data:wpuHlfgDRSvkAmk12U/msOZcqX4oLcAqBw==,iv:gFGVsyFrxtSekZNorX0YClJ7gpQf7wi5bs2bglHHZRE=,tag:op5IEAL1RulPyfksQa3/jw==,type:str]
        key: ENC[AES256_GCM,data:0R0pyxn/x2UaBwJLfyfICWeE01q3CgeW+UZQoPuKcA==,iv:2Qiy768+KV/+H9wMrUrkTbRYTc71j3KOK/2lslF8g3A=,tag:nW7XzCz0ddAdIva570FS3A==,type:str]
syncthing:
    gui-password: ENC[AES256_GCM,data:RvSw6tBMPUWvV0PQwb4D,iv:S/rxUw00jf0utPzEvtc/sK6EyCOr4Q2GH1VZ8tNkrgU=,tag:8w2ERS1ZcDTZVTRzry1p1A==,type:str]
sops:
    age:
        - recipient: age1xjnkqv32a5nqftw6pqthapnzmgjl4lnqfpxy9utqm56yzm2mvfhqzch648
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByejVmYUhZeHpkMlFMeVBi
            enpjWTJWZGdIN0JiOVc1NTFnWGFwdXJ6cEF3CjJJcmFzRUp1QUY0SVhYbmw2ZVlx
            Z3NyV3JDSVZCYzRMQWlOZWdRRjhRcmcKLS0tIDEyR2dOTFpaZlJ1Vi9vRG8xaGhZ
            TE9sWmtma3FDcjQvTzRteUt2alhQRGsKcBBHuN87XIBt58VbikgRnl998Nlkq+cc
            TiUypFR9CVCQhyMZAC01jtT6uKPghP0TdznhCXC/kW7xtuu/RUrj/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1a5aqj3jr3rqpjet9a7y077ak0ymstjjdnyfgn5m2ad4l2yuxr4aqym7d3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUWI0S0RBR1VIR2dJdjAr
            RGZ4SXFVK2ZaVmhHQXBRbXlDdDBVMmdmbkV3CkhocjdLcEU0RmI2TFNzaUJON3Mz
            NHdmSDU1dFZUcm16ZGZCM2R6anBIb28KLS0tIGhlVGdhbm5ZN1ROVm9BSVlJaDRV
            MVdmUTVjNFJFQkhNcDB0dGFiakIvVGsKRRG1TfvDHpNjbHuIp+DFlLj/xtHVhEZG
            nvghyyGk4Amq91UaafFNGGanH2wW+n3KbePd4T6NGlFeHhQKv6qqTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g45zy9m5g4e20cjejgd3x40722rlddgkmhtddrl8wyf63kt5kg7s9ke390
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRks4aGFuVGRDWWk5ellK
            cSt3a0dSVWNGamZweVk2Uk1UUjdya1YycWw4Clh3bmJ3S2tQRlovZEMxeEsxS2ty
            VlJZSXNlZ2R1U0l5UnNxNGcySC9kVEEKLS0tIHlVOXhLd280VEZVVnlYamdadHQ3
            SzZETndIeEJuWHI5Yi9xOXRya0hOc2cKZGjM+C3qa398PYup1t/3TWDW2oQ5x0Bn
            9SCj+uPn+P9TxDWMsVfMkVQXBT5qhVYW5Ih3PD5cKAQSPhaeZAXZLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ljcy90uwlfngc7vqwlf2x2ckgsdfg90c0r9yvjzpl90jkwf9g48q2leudt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeUlhYjlWbkRZY1VWV012
            WFVQamFsV1RuaDNsQnVvMGR1dHF4TTltTDB3ClJUdVRlZU80U2pWQVlNU1V2S3Vm
            ZngrNFcrQVhUUGRSbVZvVkxTQ2lDc2cKLS0tIG41MHBiRlhGR2pVNFo1SWV4YjhP
            eG1CWTlwdmp0dkRma2V2Y0VGTFMxZ1EKzMsjqVsQVDADki26do02SS0QKDb3WFL0
            ueMMT6/COL8CZ5NDaLnv1jti0zopgeBqMVQIqoyePajmbXzA9xVkDA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vl9q7u0jkzjpdqrmg4flvz2f7gyn05luv4ka60hu5l8yn4m6rujquhyc2p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRjROUzQvT0s5Q3B2SklU
            LzVaek03djhTM2NneGtzOGduZ0lEZUt2VXpRCm4yekxLdkhleDNwbWYzVlY5anRB
            TFZIVFo5Qkk4MFYzcnptZ1N1ZWxQNE0KLS0tIGYvZU50aEV0YnVoSFVUSS9IdFZo
            a3BITjVPM2JwT1BwUE1Cb3RNbVE0bkUKwKF1goRzvq1PEpV2PZt4sPKzGIrnijJo
            V+xMxE0WjvbGpLZ/E9eLn4vjlRtpFS7ARhO3oOD+drsfzDIyU9jhkg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dxsvz30sv9dvt7l0euu3eq09xs0dlleujyc40fveyxcq4hrfafmqzv4zuz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WFVMdzloNVpsNVAwMjJC
            bDFGODZhb3J5K0NHakhoOGMxQjc2MjgxZkQwCitVM0I5elN0T08vb3NlMnJDdTEv
            S09oOHpsaSthNWdOS1ozZGhhUjhSVncKLS0tIE5WYlR6L2s4emNuSHNxWnRNQnZ1
            cU0zckV0RW16REJ1RzVvOFpWTC9pZnMKWqfN0Xs4Bllcr3Esa9YdmcZ4E/2HU1rU
            t26eFDUkWJ9rKhAVa6UcZmLFtikkm7WCVQkSnpi20N8pQjzXXZzdbA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vj0wez5rdsedx9jsqcrh0wjh7tr6hyefvdltp2zapu7q7tfqkg0qez44hz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6L0pTL2FKdHJlbGd0UW8x
            MUlKenNVeTdmRlM0WFlQdGxlREhTajEvWEVVCkhiSVpPZnNxbEhqSGFhdzlzQkFu
            aWlXaWpERStlVDVra3VHWlBpWUl3SXcKLS0tIHc0VjBoUUt4Y0RXSmFXNWlYdi9U
            YU5iWmxpVHhHVmpTTW5aMXdNZ1BSRVEKfdqapVXTUkYMKT0x4m2fTthxALd+CoUI
            JMz6cOejyP8NrSSePU1hXg7KKR3D6DTqgSkaBXixTZ7xqKZ8yBL2Kg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1649y4antwgfe4fu02eppnx5gr0yc3g4lj4kwd6v9guxgxgj06y9qk7l4wl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMWdTQk03Nm5BNm5UVWd2
            RVllK2hsUVk2dXNjbllrbWNtVTdHejd0SzAwCnlFNSs1Zzc4TnNDVmdET3Y4YjFG
            dUk3RDNrVlBkM2lGc0dwMWp4NlhFWk0KLS0tIHc2b3Mra0kzellpUU5ySForMzMv
            bU9ic3BseWNKZUR0UjBrdStzUWI4SzQKgiWoViYlAo7tkfjZxh01At+sFwEkqh4z
            CQsIwRV/YhATnc6w886sgCRt0WHunhLoTmWaoPL+S86Yxs0+8fiheQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k085uuy4fv9rfpy0ne6zl9fq0j05a4fykqe26psx2ngxqrcxcu5sksxa9u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdTN5NytDR2U0bTc1YWdM
            eWpuWW5BWnVCUjZNR3VFM2NneXBIcFE1ZUVvCk1EQy9tTEM5RnBXV25vd053bkk2
            UnE5c2YzUW5YK0Q3aHJwV1FzcjErY1UKLS0tIHl3NjFrejZXcWhLdHBYTnJmKzM1
            d1o3YW5YVVJrMFNHRmFSZXhoTGZCajgKMdzuqk2126tEfmUkgdgkDOVLzrwCJq5v
            m3/x2o+A9CV2wQSFffNhigBXcRSqkol5Pbya+VAMhMD9QgKZFOPN5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tpeqfhc4n7swpgzx6qfdfxanx0uqh7nksr7eksnvjea70n8vaf5sntxu2l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUTTNrNDZFVW12aU1YcXk1
            YTI5Nks2c2phUjVXNi9jZWZFRFFjNk9aSWxvCnNvc292MzhWT29kSit5c0toWmE2
            REVNbit4dXlja0hSSGpPNXF6OWltVEUKLS0tIGpyOCthaU1penhhbWpOUmpINUpr
            Mm9LNmNLekkyUnZPUDJlK3lvdXRsb3cKk2vjaidUiwMne/+ObWUXBdnxtjWJA+0T
            FtVYqlHJ7Z+Z/tncen1LlOupjm2kbhbNb2FC/LFQxC+JYjOY5sJXWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1pux20jlyzdexztdmm3lelzn2mslxhuahae4wjy74hkxfytslsfpqj708e2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYkhaRkh2bnJFcFlqbG1v
            NTl0eXNuVytRRmREMXhCMlJwclRpN3RoTlZ3CjZwUXNiME92UFg2Nmk2bnVrazBK
            dzJUTHJUd2RkdGUxYS9NVE4wSXJ4MXcKLS0tIC9uK1pTU1hNN1Zpdmg5MC95UjV5
            WWk3TWo1U0VlMVEyRjJSdkNYdmp1U1UKlrY8vFi1HExzwmTW2d1cBP/wxrowBKbo
            oon/iX0qFaZavJuK7NHghXCnGYBEitMaCBFmn7YDL+zHbqodbExpQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1f5039syajzz75s9lkdzwnv2dsvlcp69puuaucgwt05sqjdl7hels25nsfr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eDhDaUxGZHh0MC8wZXhT
            NTVZYkltcGZWcFliSFl6NDVlQW13UXFsRm1nCjFWRlVMclBsakc1M0hnUzFTRkNE
            K0hlVk9KL1BVVUFad0pBTC8xeStscmMKLS0tIFd2SnNzdmpBbk9DZkJKVDRtYVRp
            eE5XS0oyMGRZOU5HZmNYNi9maDlJUUEKSUl1DUzIpU3rxJsxIxU68rGZS7mgj/MI
            VRlE26gXQkLw7IJyY0A6xlSho0OM3TrRECviDVdm6a7v+gWDcZc7cg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age19m6f3xtkdf3gwxqxgp9w9gyla4hk24f85l2tyjx6dxu0akzux3cs657dhz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeDZpZTU1MDVWWDVXZU5t
            UWJYRzkwMVU4cEtpZkcrM1F3c0pVd3hmMWlvCjB3Kzd5aUNlNmtHMEtHMnByZGht
            eEx0ekVFODlqbDRLTUR4UXFyNlpvbVEKLS0tIGdDK2lRTGJLZ29ZWnVybjJhaVJT
            VStiNEtZQ2tIb0dUbjA5YllzVnVtY3cKeOknW7bAiENwa/kzdOD1iV1c7gpfGDbc
            1NXLWq13vou74HcvKztuCIvmHdRckLCwOz6gA/sBUo/irqM5wQLZCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1en6vdtxspam9s3nmsyfrcrxzrzu4t9v72ztqyekpzsc35rd06a2sza7ehw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUFlQdERiYnFycFpadWFj
            ZzN3dXRCSUNGVHBEbEQwV3Zob0hjdVZPQlhvCkZDWmRZcFhUUGhZcDFCckVZMUgw
            bit6R1pqQTQzVnpLU2pRdXJ0S2RvbTAKLS0tIEFwekEyVmxuTFpUSm5jNDhQM2t3
            dVFTQXFZNWRkYlcwOTNBbEpZUEh4SkEKGKz7ioKf6HFIWJNfdZ8pjh/4Qy7nsu//
            E8p9j80rIFN9yHAX8UsxwOtOVRoBvuRId/LemdXDUkJYCJUhg1OL/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vujvq5rdzppkkdhkwyhnl6xhuvm8s5yf2wc8ke05m8jwrdwsdf0qfx5w4r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVkR1SlVBVjRubXc0UnJw
            b29kK2FVYjBYeUdQOVdtUTVnVzd5NDFVekFnClcvUlRJem1JalJEeGJKVHpLTDU1
            Z3QrT2lmVlZuRmM0a0FlZ0Z4TExTUTQKLS0tICswa1QzUVdHZVdvajU0M09xMktk
            bU1SR0ZBeVoxYStuaUdFYnZXYnlpUzQKBH0678EJOlmkK6gDC0EycGTD08xbYF0Q
            R5HSrgY0rPS9RoUsiS+YN+vDMS7jg7mA7h2Lebl0Neu912LF/rd+bA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1uyuudfya8etgztlt6hlssr9hkstyyhg65wdq3pj9rud2czzkaqqssg7yvp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TGE4UGZaUm5XaDgrTGRZ
            b1dvUmt1aExRSG5wNDdFZnpXZGJMTjNSQURzCkt5d3NmbUtIWFZBVVFKT1lVblBY
            NjA5T1QvUmN5a0J1M2YwSWY5ZU5hb00KLS0tIHlUbHFpZVFaaExIbnpNcUg2SlRW
            akxVcEZrMmpmK2VaMERMSFg5Q0xrZmcKMLlddIvv+zhw+6YxsO30JJXanM9pohnl
            4N01c+4b330kFrnBQ01sRcWu92B2ennGGjY6pnXgdCTxLp3W0vfK5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T06:45:38Z"
    mac: ENC[AES256_GCM,data:XMFW/JJpI1DyBvtEIzNhsiHBaVzbcjspUFkBu6L5Bfqns1UV3nwM/ftxwb3pseoFx9+MPUHT1rjAI9IU+AhtEJx23A1m116vnybLaDngxf9br0lJm4u+JzboeUr6ndaGoZFYEwD175CHx5yo74xZ1g4Sa6dyKcjT1wZM/CJmyhE=,iv:7dMkDgF/Qo7yj1LbCHaUbShZtD2HMMlJ2xDN48vlw70=,tag:0qgxL+0K91XZ+KSqagaBYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
