accounts:
    root:
        hashed-password: ENC[AES256_GCM,data:WmZVlgKuhhr0giWDRmvGxanJb2xHC/mCZJ4w/g/bGVjUD26rcFAC+gSJXJd0k8OMzfQG1heW/ugpVoNLze7T9SyC3EmxeOUXVQ==,iv:okbRYi3vm1CesnO01QMWOuGMw9r1wTzUoJv68pcNZHQ=,tag:XtIDWn9XqLWf3iJmFns+Ew==,type:str]
    caperren:
        hashed-password: ENC[AES256_GCM,data:8pLgyZScZIi/gia0TQskZ0gnYboNbar73MPgTWQfKweEyUI8NotJfI/v6kXvGq2l41qAPhmjFyij5uOzYTwANpd+lonvSY4zog==,iv:cva/YYDULMuM/QoTiC/7BjVUs6nAy6+4gL9XenTWDAw=,tag:F66PTiXlnfx05rIW11EEvA==,type:str]
ssh:
    ilouser:
        id_rsa: ENC[AES256_GCM,data:BuoM1E1pf9srSfWWV+bIy9H/JAQIMsucJv8T+Sky6HgSsR1WLdOX8pYJSVukuMMisSBG8DJiGy7PgzqeZohrFbkaHpc7gI0S3+803pZQjILzs9kEIrpTzqb+i5UgGPNn7Q9Rk2Etm7UlQAaUSLZg1XfCWV421YeTDFnM42bLy8Lhpb5J/GyP4iYJN5osmlQdjUbzR4wWaYIofWHjTqbNo0yNdMTDPf/bVDw+/34Xx/Xcvc90KtbO/k/gWpOam/Mq/jMoaA0IcZu7p6pu3WWFlilkeBtLefLo8nDEGi13hT2KxrB89npTNWWXf4sejQxkZgp8x1FxA8LH9v6vRunvdBRNTw/JjmtxaF8vKfjd2oxaKztLA8NROYQRpavqv6/NGlyBCU+yncq/E5dl51t7BwDwpSUvYvVEP20qH1JBKtiyuHlLOTOwTJtigOE3EuNxuEViz56Q0tVpQOcPQuSRmwdOg8hMZx/HnaDv52JVxeQHdF8jpzz3E3noB1AbRIAb84XXWVo2QLxFb8W8t5ta5cdOq/Pqte5PNXfT+2pjBIOlfg5mzA9kjH4QOZaO7zBbMj/ZD480gZY+kUMgeXgOtoLSZCPvdBbSjd7Lsd7xYbZSk6m4jOtvbTzpaFX8ZIT4ompC/+G84t3HyxE+UUeBip7mTeOJBCc1WjguKSzdBMmYZUxJAGMmWJ+TQDZSFu2m7bMmLGTgya5isqtcqGN5cGcICxIfOVfuoJ5T6vO3t2ZdUuV2U4+gfCYhtEZbsT/lhgRC0NlMWBhowCRpzhowYLHHGqmUfl5M+JTCAOS1QDmZvaGVc8BC0WWkc+162NGME1D+GRolHF44TfB5IuTQ1cfrv+VvK4DIsEslleAMCxqHPPQPGpCTcCNfe/3Yylkl/Pmogas2P8Q1fyGVTZCsS2G5wugptt8AdfdM+tvmqzlyponw3lNKe+mj1ehunJ8V93ea95cdmVikM6OLykzSrbxsejX8EgIQ0BChAFly38ot7YcmqgfqABCGeiYwOnL/90EuRmYRaMuUihbiRVzGPd5oc0OKDj5xdM2Eq/VRaODCFuhmwK5eLHB3tGab2Bin/8VGZkpWjQsd3H/UYRfPpJqjnhI3/dxD619ouZPfsTfQCVnBaZMYVKzpmeb3geNMeV1h8cDxNsAk85nAnG6RUF7xlqmgF6yUZ/vFtjUq/vCoNHsKvS5sSy73LPXljrVvZyG2K9P6dfTR4n8yYGJCoj95ahCAD4djsr9ylRzj1YTFQ7XdZGxw3GML7rmzuMS/Kk0qMKNYSlS9ru0yIL2baZmntjUKjcl0qigzO74bi3TxyoylmxXA2/80AcRU/fWi0t9g9aTJmuVztPiRQpCLsDzSS/xTjriwThx6v7tgmVwO05SdlBQ5Fk6R1nOsC+4X35l2f6pWJ91nlkfimJM3mY/MZDxWusfgXcS3SBswj59n7zX7AwykcX6/XHVWg91EfB6sRUZyHWsMxwn+i/P5aoIiO43leCD9KX5T0KjRAxa0DG092zM6pRaKEJWeBXTgcFTS5AQdMLVlt5GBHBHw2Slr6SMsUo7A1ycJqP7nw+YdLje86h4edfvbAtowhaBT3WPFoxbtAoBWqkYPgTGs/AiKRsfjecypuCm52bz8VTiw8laRkYFO0nqyYZBm4u2BbVODS6Ji9ZxNpjN/NIDh/5ffhQ611iwL2xgob/yFrjqaRyzPx1DXseMO+Lc0TMEhdSVGG9i8fTJXN8VasDDHxWCQD/ZSyERGCqIDc1+pZBjwABiECsDtQy3DI+oQ3UEPLOFHGS95Kc5+KKij3ptvf61o2J6XKEUY0jqv+puNvmjz7jqsNBY+S524G+06zzcvXsUnWQ3o1lOseFDSl4ZV+a2GiRA+AHj5gSKXTNVUMDsEu7E+4Sg1WVFKLw4KgZ0KubHYQYz56QLojv2TUL3NrK1mUfdn9jeJ01L+CIMTVjz+4UjVI/AZJA370Le01pl0ZMxaFRa0fep1Pa6MikTS7SO8NBtTtbOI2Dt/hBrXpzbicfRU/2pNJ8hEn9in0eXkZ3h0/nHm5J/OrrbVOdvQK9RkF9J0sdgmLtnAxdQjKK7r8Tg17q4vefFRtTEFPz1hV8sOrNXJZc3GRnvINE/7CVYdBQZuq7Bqze9WS+Yqzo2Z7T+cgpLTThBWlL7uGRsNcOdxQOctvoHCDFMV+9+QSH9Cc55Jdbd1T/clludubmyCJLvd5+25haXtRNSivJ/qB/ZbaZq/1PrJw2rl9XuiTczVrG/5Gwpz7a7PVrP8ydIEoTAglMdr9WICKl2cqHo1+k7HOFZluJAugNTV5aRwCvb6roKXsENH6TE68RuiYI8GXD/AzrY86TADCZroeQ+arLW+UuDqQfsnJ6MM02NcSOriAqTbwikGSzNIwkOiuZmwc5Y1pVqe1pyVDf5gN6Q=,iv:IDe6vkBvgAzfxee+/odkLk1TLZRghVEf8hqH2r3+V9I=,tag:OFCA57fQjQxc+CT9DOq+VA==,type:str]
        id_rsa_pub: ENC[AES256_GCM,data:hYdf7KifFqkHDa8UF1zvhirc2AkrYpL2VrmV2IJjHzzgbrJxshdA629mTXwXwXORbLwNcMpRR7DFLyHCRDu5cWsxluZ04rNU9sJFmL+6pPUonaa4Wc+9z5VysV8UItY/BZ/5mOMQ2ph/wMQ3pkFnBD58vOFOYsmZ7OCir5dQZfm8GdGDX76bOlOI/CAg/LtwFveHK4trY3EUkxbJQ1soZdpm7ML/7bDN52klaS/EEgwk+FJrNAcm8M+N3kMSZoJyJW7c1OG81d4G84tryt2fa7s2HGT79IX6h4wI0GGu+bl87MgmFC48KdvjPdWowfh2QxkphSLduYQ4ss4EQYgJrmkQznQtt67acCFxNrEyE5psSMQPXtgAbwV94xeqtc+QHzmjHAwICTzk7Q4sFF85cDV54ZyoQDYdfubjpJ6mdE65dftN2eYD/5ywdTq09vRpnlh24PTrp7nn4H+Yddakv5KGhQOnj0p6JHNytXEClmiqxANrsYyhKvZe9gS+5w1RIcrsv9dHr5uL7Q==,iv:PQiVjFf2LlOKa6i7V/DcxYU54m/AbJGwTwUmA9asKI4=,tag:y27R0sMuOno0Al9iD3+MsQ==,type:str]
bots:
    perrencloudbot:
        api-token: ENC[AES256_GCM,data:mbIX/9Kgzfb8ZcyjTD8ltrAGCe471DHh/HeqDpNx8S4XeQWvExTLhKRwsfyKSg==,iv:vqNiR/eS41bpMzgJCMZd+AsM7wo/0UtVjsP2kPUpDAM=,tag:3hRmAlNb//bcmNR2NtQc4A==,type:str]
        chat-ids: ENC[AES256_GCM,data:InyQ3YCCCQH2orsfi2E=,iv:0iAASgJDNg6XrmL+96msW3ubz2CpHMWHEd1Q9kDRFFw=,tag:WLqeFSoictK6SKGOlDR4Iw==,type:str]
backups:
    primary:
        repository: ENC[AES256_GCM,data:qGtrxtrnimS4+Gf5S0VbcTher0eWUiEEYbvdd4W5+WtI,iv:8ptER7muCz/nQryiy+WZVDLhwW+SaLZuaAOYGOQecMc=,tag:+aWH5mi+G2+KF6NOv23KpA==,type:str]
        id: ENC[AES256_GCM,data:wpuHlfgDRSvkAmk12U/msOZcqX4oLcAqBw==,iv:gFGVsyFrxtSekZNorX0YClJ7gpQf7wi5bs2bglHHZRE=,tag:op5IEAL1RulPyfksQa3/jw==,type:str]
        key: ENC[AES256_GCM,data:0R0pyxn/x2UaBwJLfyfICWeE01q3CgeW+UZQoPuKcA==,iv:2Qiy768+KV/+H9wMrUrkTbRYTc71j3KOK/2lslF8g3A=,tag:nW7XzCz0ddAdIva570FS3A==,type:str]
syncthing:
    gui-password: ENC[AES256_GCM,data:RvSw6tBMPUWvV0PQwb4D,iv:S/rxUw00jf0utPzEvtc/sK6EyCOr4Q2GH1VZ8tNkrgU=,tag:8w2ERS1ZcDTZVTRzry1p1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVTdsSWw1YXo1Z0dFVHU3
            WnQzd2JsV0pDNkNncWhvTVpEYUpua2lNRndRCkJRdk0xYlhMRjFoMXlOQ2RrOXBu
            Z1JDUXpiNjJlS3h4N3Y0UTdlRm84T2sKLS0tIG5EU09ZQVkzUlBVMmxZUHdtNDNJ
            L1Ywd3JxQ3hGa2lNSXFhR1RaT3dPRVEKyqPi7+XSNkKEWKZWz62y2CTMbyxwVuDm
            fPrJh/Oget7A1ZaCrtqsKJH5PkovhkYCV7UR4k50zvZWRWrhgOiszg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1xjnkqv32a5nqftw6pqthapnzmgjl4lnqfpxy9utqm56yzm2mvfhqzch648
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcis1VjFLTmQ3djg5WXBM
            b1hja3I5dTV2dGZWYThKclI2eXBob3dpTHdBCjZtMVlIK3VLcGVrZ09vN3ljcEt3
            bUF5NXZrMlhqenI5YlZ6TCtCLzlqRWsKLS0tIDF2VFhscnBtS0FhN3ZncHB4cVRL
            SkJFdTkxNVo3VFhpZjFydzNIL0NldW8KXVwSOmJ4Ef4RDvHypySb80YoiNMYqX2V
            c/jgpi+FsUBJPg+hDfDK4/pNEPVZdWDqSfJhLgUVjqRPd9y+ugL9Wg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a5aqj3jr3rqpjet9a7y077ak0ymstjjdnyfgn5m2ad4l2yuxr4aqym7d3d
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQkNlZjR3R1FIaWJ0N0Zx
            b1VYVTRwaDNQcitYVXNuNHBrRTZKOVIvT2tZClZlT2dGYVZLSEpIZm5OcXNJTlFi
            eEt0UURMM2R1MFFicHRHZ0ZBQ1FIVGMKLS0tIENzUkFOclpZUXFDMkZOaVJ6UUhU
            UjRSWm5qcWxiNGFKQWJZSWxYUFkwMTQKzeN23Epwf0k7SLqCE23C0NuugPuJABVD
            XHHPgZqL3MzaseSBfDYs5pyk5kXCs3jtJgNlfywdt5kw287qfKBRvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g45zy9m5g4e20cjejgd3x40722rlddgkmhtddrl8wyf63kt5kg7s9ke390
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aFBscDBwNVBoYzlwZk1O
            bUh1UmNwanFMNFFxWlBaR2N4SXpYNDV5RHc4CllkQzFvbkEzdWlreXNTNVVqeEVi
            bExvLy9hUzU5TVZSdUtvNlIzTTU5MEEKLS0tIGRrUU5JYXN6VHJ3MUxMV3F2clFu
            alVwYWFVQnpmbldVMWxnSnQ1dm9FbU0KEGnNJVl9Da5wTig7GRbAM3Kz+N5CPxcD
            /OxuBSv08dsScB80jKGbn6UMIrEOweU4H+QdcbZj+9aBT1hfNUOoTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ljcy90uwlfngc7vqwlf2x2ckgsdfg90c0r9yvjzpl90jkwf9g48q2leudt
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOR09mZE1HMmpUMXdTa0R2
            Mm9BZGdXVHpHb1Q2Ylo3TGlId1BpRVRkTnhVClBzSGR3d0dkc3drNjVhb0FONzRh
            eEgyaUtnd3VHUlhoZldDZ2RiY2FyY3cKLS0tIFJKNkFLaEF0Y3N4ajRldS9vd3Qx
            MnFIQzdVWWJMd0xSdTh1SWpIOHIxdlkK/Scv3D0XccA/da38jGjXYJNP2o3GTLvz
            HmfXpuJpFeQVNg8NslSTTTtHeydP+4J5mgwYLRL8jdkAI7NYyrGDDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vl9q7u0jkzjpdqrmg4flvz2f7gyn05luv4ka60hu5l8yn4m6rujquhyc2p
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMzJXcE8zdStaelhXNnNU
            RDFIbXdRT09sQ2s4cUlZTUNqSDNiT3RwNjFjCmI1QXU3SXEvQVdMbk1Lc1d6aDRT
            Mm1WNkZrclpaRjZpdG1CdUhnK0IxN1kKLS0tIEFQVTRwV2I2ZUpWVUZiVDVaNHN6
            YXBhSVF1SHhxYy9oYnZtNDVybHZIZG8KJXvRX4+bMB3hYVWK+jhfpnnyZ06Jd1Ok
            li7zRS1MiRoI7iThcjlBN1T25jaktL5DzKfq7lNut2f9BQ0sIcc57Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dxsvz30sv9dvt7l0euu3eq09xs0dlleujyc40fveyxcq4hrfafmqzv4zuz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSlJHYzhrNnRndktDd0Vj
            UXJTSWQxOVgvejBEUEZqT2x3eWFjNG5NSHpRCk4zNFpXei9JNHFubjZaalhuRFFU
            c0VSbVJjK3Z4RU1XUTROVkpZMlBRWWcKLS0tIEhNam1PVHZVWkVQUWR6NVU1ZHpH
            bitYRFFWeW4ybWZLUDlwZnd1ZzZZbkUKPnfLMVej+Ty7ykjKXTiSAlANjYMu0EEh
            qAcPTG94wkqrN5FcyDwC9YHsmW22i6uSDyGxlxMhH7VSxPdMU48BCg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vj0wez5rdsedx9jsqcrh0wjh7tr6hyefvdltp2zapu7q7tfqkg0qez44hz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeWVxaXBucUpYMHAwYzVu
            THBNbDNVWjNBU3Vva1Bkc0tRd3puSy9hMlRJCnhkWnhNM2V0azd4cVB3TDFqT0Va
            T1EvUzlQWEQwN0xldWUvdXZ6YmVWa0EKLS0tIGNVNHZER3JuajM3NEFQTm02alRZ
            ZkpkV0J1NGtRVFIvMHJwT0c1TitBT0UKWIT3R4/OQwj9Hybqf72QCBOx6pMhAbMA
            0zutzWSJxxM3/NETOA3kzNzqTxjH+PFVuYnz4b1Y6zqpgR3z4uA7Cw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hu2jmgzzpjmc8nhpgfslsqma05l8n445sk28f8z5dqu5nr0e3pmqt5f8yw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcVNoajE0MlhpNFpEdmFi
            NXA1VDhmUnI5M3pQbXd4TXBpemdwM1dYWkdJClRKYjYzN2xTa0czQkJLQ241VTJq
            UnQvS3BnVGUxNHdDVWNidnhpUVB2WFEKLS0tIGh5bUEwSU5WdkZBYUZjajc5YXRR
            OXFndlhTRDhya3RWdlUxdWd4NEdnSFEKuVBEsjHxHudQEyUQEMtVoE/Eaxqyj+uo
            a5RGboPXy3zhaTbNnSQdqhsqX3BTRt1A1xcXyxN0ZuZZHq3Q0UlUPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ldrn70e09s99p0frlkpywpns0sl6vr4y4kdxr9r47wuh9swq2faq30au2h
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmU0VBT0hxaUEyd2pjdUxQ
            a0NUM2lEUExiU3FXTnVUcng0SitoMDlrYWhFCnoraDh6dlFvbHlmM1NIMlJ0M2Rx
            aDJNMENIQ3ZOb1M2Nm14ZG5VK3ZJak0KLS0tIGYvN1hxSkFoNkwyUmFaUU5yblFW
            ZjVhZEJIMlRVNHgwcFVhMFB1ejhScDgKn6Nk+LVJh0a/z9TmYZ6xtcnVOStXLPU7
            l7RaiXh4Hfy7a102WMGHJ6tSDAVvWKbms/RB3VW09E12UHNtF2DnVQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age17k70g4yrrkcuzshwefpx0ll3hp9nyytfcgrfd4cv3wxvn0g60uusw4njfj
    lastmodified: "2026-02-06T06:45:38Z"
    mac: ENC[AES256_GCM,data:XMFW/JJpI1DyBvtEIzNhsiHBaVzbcjspUFkBu6L5Bfqns1UV3nwM/ftxwb3pseoFx9+MPUHT1rjAI9IU+AhtEJx23A1m116vnybLaDngxf9br0lJm4u+JzboeUr6ndaGoZFYEwD175CHx5yo74xZ1g4Sa6dyKcjT1wZM/CJmyhE=,iv:7dMkDgF/Qo7yj1LbCHaUbShZtD2HMMlJ2xDN48vlw70=,tag:0qgxL+0K91XZ+KSqagaBYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
